version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./db/postgresql:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend:rw
    ports:
      - '3000:3000'