version: '3.4'

services:
  db:
    image: postgres:12.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./db/postgresql:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
      target: prod
    command: gunicorn --bind :8000 --workers 3 MemoriaFotografica.wsgi:application
    environment:
      DJANGO_SECRET_KEY: "CHANGE-ME-PLEASE"
      DJANGO_DEBUG: "False"
      DJANGO_DB_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: unless-stopped
  nginx:
    image: nginx:1.19.2
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/certs:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
  certbot: 
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot