version: "3.4"

services:
  db:
    image: postgres:12.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
  backend:
    image: leit/backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SECRET_KEY: "ic8ub6c3x@1!%*-+tan#n@t+c6lr=gu=po5j5cl3ytodjwxs0r"
      DJANGO_DEBUG: "True"
    restart: unless-stopped
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - rabbitmq
      - celery_worker
      - minio1
    ports:
      - 8000:8000
      - 5678:5678
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/frontend/src:rw
      - ./frontend/package.json:/app/frontend/package.json:rw
      - ./frontend/package-lock.json:/app/frontend/package-lock.json:rw
    ports:
      - "3001:3000"
    stdin_open: true
  rabbitmq:
    image: rabbitmq:3.7-alpine
  celery_worker:
    image: leit/backend:latest
    command: celery -A MemoriaFotografica worker --loglevel=INFO
    environment:
      DJANGO_SECRET_KEY: "ic8ub6c3x@1!%*-+tan#n@t+c6lr=gu=po5j5cl3ytodjwxs0r"
    ports: []
    depends_on: 
      - rabbitmq
      - db
    environment: 
      DJANGO_SECRET_KEY: "ic8ub6c3x@1!%*-+tan#n@t+c6lr=gu=po5j5cl3ytodjwxs0r"
  minio1:
    image: minio/minio:RELEASE.2021-07-30T00-02-00Z
    command: server --console-address ":9001" /data1
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./data1-1:/data1
  

