version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./db/postgresql:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: unless-stopped
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend:rw
    stdin_open: true
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/static/:/data/nginx/cache