version: "3.4"

services:
  db:
    image: postgres:12.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
  backend: &python
    build:
      context: ./backend
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SECRET_KEY: "ic8ub6c3x@1!%*-+tan#n@t+c6lr=gu=po5j5cl3ytodjwxs0r"
      DJANGO_DEBUG: "True"
    restart: unless-stopped
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - rabbitmq
      - celery_worker
    ports:
      - 8000:8000
      - 5678:5678
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/frontend/src:rw
      - ./frontend/package.json:/app/frontend/package.json:rw
      - ./frontend/package-lock.json:/app/frontend/package-lock.json:rw
      - ./frontend/.env-cmdrc:/app/frontend/.env-cmdrc
    ports:
      - "3001:3000"
    stdin_open: true
  rabbitmq:
    image: rabbitmq:3.7-alpine
  celery_worker:
    <<: *python
    command: celery -A MemoriaFotografica worker --loglevel=INFO
    ports: []
    depends_on: 
      - rabbitmq
      - db

