# Generated by Django 2.0.7 on 2018-07-14 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MetaData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('uploadDate', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published')),
                ('tags', models.ManyToManyField(to='MetaData.Metadata')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='pictures',
            field=models.ManyToManyField(to='Gallery.Photo'),
        ),
    ]
