# Generated by Django 2.2.24 on 2021-08-21 16:59

import Gallery.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MetaData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('censure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Gallery.models.gen_uuid)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date published')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('censure', models.BooleanField(default=False)),
                ('aspect_h', models.IntegerField(blank=True, default=1)),
                ('aspect_w', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ManyToManyField(blank=True, to='Gallery.Category')),
                ('comments', models.ManyToManyField(blank=True, to='Gallery.Comment')),
                ('metadata', models.ManyToManyField(blank=True, to='MetaData.Metadata')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='MetaData.License')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_details', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'usuario'), (2, 'foto'), (3, 'comentario')])),
            ],
        ),
        migrations.CreateModel(
            name='TagSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.BooleanField(default=False)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagsuggestion_metadata', to='MetaData.Metadata')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagsuggestion_photo', to='Gallery.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='report',
            field=models.ManyToManyField(blank=True, to='Gallery.Reporte'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ManyToManyField(blank=True, to='Gallery.Reporte'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection', models.BooleanField(default=False)),
                ('thumbnail', models.CharField(blank=True, max_length=60)),
                ('aspect_h', models.IntegerField(blank=True, default=1)),
                ('aspect_w', models.IntegerField(blank=True, default=1)),
                ('pictures', models.ManyToManyField(blank=True, to='Gallery.Photo')),
            ],
        ),
    ]
