# Generated by Django 2.1.5 on 2020-03-14 14:24

import Gallery.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MetaData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('collection', models.BooleanField(default=False)),
                ('thumbnail', models.CharField(blank=True, max_length=60)),
                ('aspect_h', models.IntegerField(blank=True, default=1)),
                ('aspect_w', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('censure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Gallery.models.gen_uuid)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=True)),
                ('censure', models.BooleanField(default=False)),
                ('permission', Gallery.models.PatchedMultiSelectField(choices=[('CC BY', 'Atribución'), ('CC BY-SA', 'Atribución-CompartirIgual'), ('CC BY-ND', 'Atribución sin Derivadas'), ('CC BY-NC', 'Atribución No Comercial'), ('CC BY-NC-SA', 'Atribución NoComercial-CompartirIgual'), ('CC BY-NC-ND', 'Atribución NoComercial-SinDerivadas')], max_length=56)),
                ('aspect_h', models.IntegerField(blank=True, default=1)),
                ('aspect_w', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ManyToManyField(blank=True, to='Gallery.Category')),
                ('comments', models.ManyToManyField(blank=True, to='Gallery.Comment')),
                ('metadata', models.ManyToManyField(blank=True, to='MetaData.Metadata')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'usuario'), (2, 'foto'), (3, 'comentario')])),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='report',
            field=models.ManyToManyField(blank=True, to='Gallery.Reporte'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ManyToManyField(blank=True, to='Gallery.Reporte'),
        ),
        migrations.AddField(
            model_name='album',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='Gallery.Photo'),
        ),
    ]
