# Generated by Django 3.2 on 2021-09-11 14:07

import Gallery.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Gallery.models.gen_uuid)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date published')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('censure', models.BooleanField(default=False)),
                ('aspect_h', models.IntegerField(blank=True, default=1)),
                ('aspect_w', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('identity_document', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=40)),
                ('resolved', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('photos', models.ManyToManyField(to='Gallery.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('censure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gallery.photo')),
                ('report', models.ManyToManyField(blank=True, to='WebAdmin.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pictures', models.ManyToManyField(blank=True, to='Gallery.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection', models.BooleanField(default=False)),
                ('thumbnail', models.CharField(blank=True, max_length=60)),
                ('aspect_h', models.IntegerField(blank=True, default=1)),
                ('aspect_w', models.IntegerField(blank=True, default=1)),
                ('pictures', models.ManyToManyField(blank=True, to='Gallery.Photo')),
            ],
        ),
    ]
