# Generated by Django 3.2 on 2021-09-11 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MetaData', '0002_auto_20210911_1109'),
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='metadata',
            field=models.ManyToManyField(blank=True, to='MetaData.Metadata'),
        ),
        migrations.AddField(
            model_name='photo',
            name='report',
            field=models.ManyToManyField(blank=True, to='WebAdmin.Report'),
        ),
    ]
