# Generated by Django 2.1.5 on 2020-07-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_auto_20200629_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
