# Generated by Django 2.2.13 on 2021-01-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_auto_20200630_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='resolution_details',
            field=models.TextField(default=''),
        ),
    ]
