# Generated by Django 2.0.5 on 2018-09-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gallery.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('photo', models.ManyToManyField(to='Gallery.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gallery.Photo')),
            ],
        ),
    ]
