import * as alert from "./alert";
import * as auth from "./auth";
import * as curador from "./curador";
import * as home from "./home";
import * as misc from "./misc";
import * as photoDetails from "./photodetails";
import * as requestPhoto from "./requestPhoto";
import * as search from "./search";
import * as upload from "./upload";
import * as user from "./user";
import * as metadata from "./metadata";

export { alert };
export { auth };
export { upload };
export { home };
export { photoDetails };
export { requestPhoto };
export { misc };
export { search };
export { curador };
export { user };
export { metadata };