# Generated by Django 2.1.5 on 2020-06-29 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photorequest',
            old_name='email_sent',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='photorequest',
            old_name='comuna',
            new_name='district',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
