# Generated by Django 2.2.20 on 2021-07-24 18:58

import Users.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gallery', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Aprobación'), (2, 'Edición'), (3, 'Censura')], default=1)),
                ('content', models.PositiveSmallIntegerField(choices=[(1, 'usuario'), (2, 'foto'), (3, 'comentario')], default=1)),
                ('message', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('completed_registration', models.BooleanField(default=True, verbose_name='completed_registration')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('generation', models.CharField(blank=True, max_length=5, verbose_name='generation')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'colaborator'), (2, 'curator'), (3, 'admin')], default=1)),
                ('rol_type', models.PositiveSmallIntegerField(choices=[(1, 'Alumno'), (2, 'Ex-Alumno'), (3, 'Académico'), (4, 'Ex-Académico'), (5, 'Funcionario'), (6, 'Externo')], default=6)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('public_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('albums', models.ManyToManyField(blank=True, to='Gallery.Album')),
                ('comments', models.ManyToManyField(blank=True, to='Gallery.Comment')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('notifications', models.ManyToManyField(blank=True, to='Users.Notification')),
                ('photos', models.ManyToManyField(blank=True, to='Gallery.Photo')),
                ('report', models.ManyToManyField(blank=True, to='Gallery.Reporte')),
                ('tags_suggestions', models.ManyToManyField(blank=True, to='Gallery.TagSuggestion')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', Users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'activated'), (1, 'available')], default=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
