# Generated by Django 3.2 on 2021-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaData', '0002_auto_20210911_1109'),
        ('WebAdmin', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report',
            field=models.ManyToManyField(blank=True, to='WebAdmin.Report'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags_suggestions',
            field=models.ManyToManyField(blank=True, to='MetaData.TagSuggestion'),
        ),
    ]
